version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install --user tox
      - run: ~/.local/bin/tox

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
    
# version: 2.1

# orbs:
#   python: circleci/python@0.2.1

# jobs:
#   build-and-test:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#       - run:
#           command: ./manage.py test
#           name: Test

# workflows:
#   main:
#     jobs:
#       - build-and-test
